### ISSUE TITLE
Points as map features are not visible on project details page

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#2164]
**Describe the bug**
when I create a project for MSF Austria demo where most of the features to be surveyed are point features (POIs and amenities). The project can be created but the features are not visible on project details page. 

**To Reproduce**

1. Go to 'create project'
2. Create a project using points as map features
3. Use divide by square as splitting option
4. Go to project details page
5. See error

**Expected behavior**
The features should be visible on project details page

**Screenshots**

![Image](https://github.com/user-attachments/assets/3eafcbfe-9655-4fde-bdd9-6d65c796f802)

**Additional context**
Check the behavior on https://dev.fmtm.hotosm.org/project/101

**Comment by spwoodcock** [comment]
#2154 we have a bit of work to do making FMTM functional for mapping points.

So far we only focused on polygons.

How urgent is this project? 🙏

**Comment by manjitapandey** [comment]
I am not sure on priority. Ivan is providing demo this week where the clients are mostly mapping point features. I will forward you the email.

**Comment by spwoodcock** [comment]
Is there any chance you can upload the data here, for easier debugging when we address this?

I think its actually a bug related to the data extract, as I managed to create a point data project previously and at least display the data on the map

**Comment by manjitapandey** [comment]
Task boundary:

[Bharatpur task boundary.zip](https://github.com/user-attachments/files/18731500/Bharatpur.task.boundary.zip)

[MSF project point features.zip](https://github.com/user-attachments/files/18731520/MSF.project.point.features.zip)

**Comment by spwoodcock** [comment]
It's a frontend issue, as the point are actually there, but don't display on the map (no style probably)

![Image](https://github.com/user-attachments/assets/2c8a00ee-76cf-4fba-95be-0e8bb569d622)

The downloaded data
[3_map_features.zip](https://github.com/user-attachments/files/18738479/3_map_features.zip)

**Comment by manjitapandey** [comment]
@spwoodcock , now all the projects are shown as point features. I just created a project with building map feature downloaded from osm, which i expected to be on polygon format. However, I can see the buildings are in point format. 
I don't suppose this is expected behavior.

**Comment by spwoodcock** [comment]
All projects or just newly created projects are displaying as points?

I will look into it 👍

Should we make a new PATCH release soon after fixing this?

**Comment by manjitapandey** [comment]
This is for newly created projects. Old projects are showing the polygon boundary. 
Have we pushed the changes on main or prod too or is it only on dev server?? If only on dev, not big issue but if its on staging or prod, we may need patch release.

**Comment by spwoodcock** [comment]
No this isn't on prod, don't worry =)

A hotfix would be to fix prod, while PATCH releases are just in the regular release cycle 😉

**Comment by manjitapandey** [comment]
Yes there are many bug fixes and features that needs to be on prod as well as on Tokha instance too. So we need to decide on patch release soon.

**Comment by spwoodcock** [comment]
I think previously we were creating data extracts but not actually displaying any of the point data!

So we probably have a few projects with some point data in there, but they don't show and were not mapped.

![Image](https://github.com/user-attachments/assets/42194638-b7ce-4e38-9889-c77f2fc2fa5d)

It makes sense to be able to map both right? We create entities in ODK for both geometry types in parallel.

If we allow for mapping mixed geometry types though, this causes a dilemma for the draw geometry functionality as we have it.

Perhaps we need to let the user select which type of geometry type they want to draw (a draw toolbar), then allow them to submit for any type of drawn geometry?

**Comment by spwoodcock** [comment]
I think this issue is fixed though & we can create new issues for the points above 👍

**Comment by manjitapandey** [comment]
Sorry for the confusion, I didn't make it clear earlier maybe. But have you looked at those projects on mapper's page. Though they are visualised as polygon on project details page, they as seen as points on mapper's page. 
Its the same behavior for custom uploaded polygons as map features, its shown as polygon on project details page and as points on mapper's page.

**Comment by manjitapandey** [comment]
Clarifying requirement again: 

- If user upload points as map features during project creation: visualise those points on project details page and mapper's page. Remaining workflow similar to those of polygons. - expected 👍 
- If user uploads polygons only as map features : visualise those as polygons on project details page and mapper's page. -Current behavior is  polygon is visualised as points on mapper's page - Not expected behavior
- If user uploads both point and polygon: Visualise them as they are uploaded. 

Same will be the behavior for when user fetch map features from osm. 
Hope this makes things clear.

**Comment by spwoodcock** [comment]
I made a temp fix to default to Polygons for now.

Will be continued in https://github.com/hotosm/fmtm/issues/2220

**Comment by manjitapandey** [comment]
Though temporary fix is made, its still shown as points on mapper frontend for the building features fetched from osm.

**Comment by manjitapandey** [comment]
I just created a new project and the features were points  for the building features fetched from osm. I haven't tried by uploding custom map features though. 

For tokha, the behavior should be features should be polygon and this is non negotiable and my concern is when we pull whole staging server to tokha, it gonna create mess.

**Comment by spwoodcock** [comment]
Does Tokha have all the projects made already, or still needs some new ones?

If they are already made, we just update the db value as mentioned

**Comment by NSUWAL123** [comment]
> Does Tokha have all the projects made already, or still needs some new ones?
> 
> If they are already made, we just update the db value as mentioned

There will be around 3-4 projects to be made
